openapi: 3.0.0
info:
  title: API de Cines y Películas
  description: API para consultar información de cines y películas en Madrid.
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /cines:
    get:
      summary: Obtener listado de cines
      responses:
        '200':
          description: Listado de cines
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nombre:
                      type: string
                      example: "Cines Callao"
                    direccion:
                      type: string
                      example: "Plaza Callao 3 28013 Madrid"
                    url:
                      type: string
                      example: "https://www.sensacine.com/cines/cine/E0146/"
                    peliculas:
                      type: array
                      items:
                        type: object
                        properties:
                          titulo:
                            type: string
                            example: "La virgen roja"
                          horarios:
                            type: array
                            items:
                              type: string
                              example: "16:00"
                          fecha:
                            type: string
                            example: "2024-10-09"
        '500':
          description: Error en la solicitud HTTP o no se encontraron cines
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error en la solicitud HTTP o no se encontraron cines"
  /peliculas:
    get:
      summary: Obtener listado de películas en todos los cines
      responses:
        '200':
          description: Listado de películas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    cine:
                      type: string
                      example: "Cines Callao"
                    direccion:
                      type: string
                      example: "Plaza Callao 3 28013 Madrid"
                    titulo:
                      type: string
                      example: "La virgen roja"
                    horarios:
                      type: array
                      items:
                        type: string
                        example: "16:00"
                    fecha:
                      type: string
                      example: "2024-10-09"
        '500':
          description: Error en la solicitud HTTP o no se encontraron cines
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error en la solicitud HTTP o no se encontraron cines"
  /horarios:
    get:
      summary: Obtener horarios de una película en un cine concreto
      parameters:
        - in: query
          name: cine
          schema:
            type: string
          required: true
          description: Nombre del cine
        - in: query
          name: pelicula
          schema:
            type: string
          required: true
          description: Título de la película
      responses:
        '200':
          description: Horarios de la película en el cine
          content:
            application/json:
              schema:
                type: object
                properties:
                  cine:
                    type: string
                    example: "Cines Callao"
                  direccion:
                    type: string
                    example: "Plaza Callao 3 28013 Madrid"
                  titulo:
                    type: string
                    example: "La virgen roja"
                  horarios:
                    type: array
                    items:
                      type: string
                      example: "16:00"
                  fecha:
                    type: string
                    example: "2024-10-09"
        '400':
          description: Parámetros 'cine' y 'pelicula' son requeridos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Parámetros 'cine' y 'pelicula' son requeridos"
        '404':
          description: No se encontraron horarios para la película en el cine especificado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No se encontraron horarios para la película en el cine especificado"
        '500':
          description: Error en la solicitud HTTP o no se encontraron cines
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error en la solicitud HTTP o no se encontraron cines"
  /cines_pelicula:
    get:
      summary: Obtener listado de cines que emiten una película concreta
      parameters:
        - in: query
          name: pelicula
          schema:
            type: string
          required: true
          description: Título de la película
      responses:
        '200':
          description: Listado de cines que emiten la película
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    cine:
                      type: string
                      example: "Cines Callao"
                    direccion:
                      type: string
                      example: "Plaza Callao 3 28013 Madrid"
                    horarios:
                      type: array
                      items:
                        type: string
                        example: "16:00"
                    fecha:
                      type: string
                      example: "2024-10-09"
        '400':
          description: Parámetro 'pelicula' es requerido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Parámetro 'pelicula' es requerido"
        '404':
          description: No se encontraron cines que emitan la película especificada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No se encontraron cines que emitan la película especificada"
        '500':
          description: Error en la solicitud HTTP o no se encontraron cines
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error en la solicitud HTTP o no se encontraron cines"